[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  functions = "netlify/functions"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/openrouter-proxy-direct"
  to = "/.netlify/functions/openrouter-proxy-direct"
  status = 200 